apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
  labels:
    app: {{ .Values.projectname }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.name }}-http
  selector:
    app: {{ .Values.service.name }}
